apiVersion: apps/v1
kind: Deployment
metadata:
  name: systematic-app
  namespace: hackathon-app
  labels:
    app: systematic-app
    beast-mode: "systematic-excellence"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: systematic-app
  template:
    metadata:
      labels:
        app: systematic-app
        beast-mode: "systematic-excellence"
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: beast-mode-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault