apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: systematic-app-hpa
  namespace: hackathon-app
  labels:
    app: systematic-app
    beast-mode: "systematic-excellence"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: systematic-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80