apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: systematic-app-netpol
  namespace: hackathon-app
  labels:
    beast-mode: "systematic-excellence"
spec:
  podSelector:
    matchLabels:
      app: systematic-app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 80
  egress:
  - {} # Allow all egress for demo purposes