apiVersion: v1
kind: Service
metadata:
  name: ai-microservice
  namespace: hackathon-app
  labels:
    app: ai-microservice
    component: backend
    hackathon: gke-turns-10
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ai-microservice